name: Super-Linter-MNB-Model-ML

on: push

jobs:
  super-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure Python 
      uses: actions/setup-python@v2
      with: 
        python-version: '3.10.6'
      
    - name: Install flake8
      run: pip install flake8
      
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      env: 
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
